# Generated by Django 2.0.3 on 2018-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'جندي'), (1, 'صف ضابط')], default=4)),
                ('name', models.CharField(max_length=50)),
                ('attendance', models.IntegerField(choices=[(1, 'متواجد'), (2, 'اجازة'), (3, 'راحة'), (4, 'مأمورية'), (5, 'مستشفي'), (6, 'غياب')], default=0)),
                ('sector', models.IntegerField(choices=[(1, 'تخطيط'), (2, 'ادارة عسكرية'), (3, 'شئون قانونية'), (4, 'نمظيم و تسليح'), (5, 'افراد'), (6, 'ادارة محلية'), (7, 'سجلات'), (8, 'تعبئة')], default=0)),
                ('mil_numb', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
