# Generated by Django 2.0.5 on 2018-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpeople', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='attendance',
            field=models.IntegerField(choices=[(1, 'متواجد'), (2, 'اجازة'), (3, 'راحة'), (4, 'مأمورية'), (5, 'مستشفي'), (6, 'غياب')], default=1),
        ),
    ]
